### ISSUE TITLE
Develop new New Horizons metrics report

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/pds-report-service#6]
## 💡 Description

UPDATE 2/15/2022
Based on the submitted R&A proposals, most required are Pluto data. It may be worth emphasizing Pluto and MU69 data, I doubt it is a high demand for cruise data.  

All the Pluto data have "pluto" somewhere in the URL; all the MU69 data have "kem" somewhere in the URL. Here's a new set of regexp patterns:

nh-.*alice.*pluto
nh-.*leisa.*pluto
nh-.*lorri.*pluto
nh-.*mvic.*pluto
nh-.*pepssi.*pluto
nh-.*rex.*pluto
nh-.*sdc.*pluto
nh-.*swap.*pluto

nh-.*alice.*kem
nh-.*leisa.*kem
nh-.*lorri.*kem
nh-.*mvic.*kem
nh-.*pepssi.*kem
nh-.*rex.*kem
nh-.*sdc.*kem
nh-.*swap.*kem

---
ORIGINAL REQUEST

We have been asked to supply some download metrics for the New Horizons instrument data.  Specifically, we've been asked for: "Number and volume of downloads. Number of users of each instrument. If possible, distribution of IP addresses by country", broken down by instrument.

For all the log files you have, can you send us a monthly breakdown for each instrument showing number of requests, download volume, unique IPs (as a representation of "users" unless you have something better to indicate that", and if possible, number of users by geographic region, for each of the eight New Horizons instruments, with separate totals for primary and extended mission?

There are over 250 NH data sets, but the instrument data can be selected for both primary and extended missions using the following patterns (typical regular expression syntax):

Alice: nh-.*alice
LEISA: nh-.*leisa
LORRI: nh-.*lorri
MVIC: nh-.*mvic
PEPSSI: nh-.*pepssi
REX: nh-.*rex
SDC: nh-.*sdc
SWAP: nh-.*swap

These patterns will also match extended mission data sets. To select extended mission data sets specifically:

Alice: nh-.*alice.*kem
LEISA: nh-.*leisa.*kem
LORRI: nh-.*lorri.*kem
MVIC: nh-.*mvic.*kem
PEPSSI: nh-.*pepssi.*kem
REX: nh-.*rex.*kem
SDC: nh-.*sdc.*kem
SWAP: nh-.*swap.*kem

The pattern for selecting primary data _only_ would require negation logic that depends on what flavor of regular expression you're using.

The deadline for this is EOB (PST) Thursday, 17 February 2022.

Please let me know if this is doable, and if there are any questions. Many thanks!

-Anne.

**Comment by tloubrieu-jpl** [comment]
@c-suh sent an email for review to @jordanpadams and @viviant100

**Comment by c-suh** [comment]
sent Anne files for New Horizons - Extended and New Horizons - Pluto
