### ISSUE TITLE
Develop new OREx metrics report

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pds-report-service#7]
similar to https://github.com/NASA-PDS/pds-report-service/issues/6

Need by 2/17/2022

**Comment by c-suh** [comment]
@jordanpadams who would I reach out to for the URLs (and ballpark dataset IDs) of OREx instrument data?

**Comment by c-suh** [comment]
What I've gleaned so far from links on our OREx data release pages:
| instrument | data URLs |
| :---------- | :---------- |
| OCAMS | https://sbnarchive.psi.edu/pds4/orex/orex.ocams/ |
| OLA | https://sbnarchive.psi.edu/pds4/orex/orex.ola/ |
| OTES | https://sbnarchive.psi.edu/pds4/orex/orex.otes/ |
| OVIRS | https://sbnarchive.psi.edu/pds4/orex/orex.ovirs/ |
| TAGCAMS | https://sbnarchive.psi.edu/pds4/orex/orex.tagcams/ |

However, I don't see any parts of these URLs in the logs.

**Comment by jordanpadams** [comment]
@c-suh I will try to take a look. I wonder if for some reason we haven't been getting those logs. Those URLs for OREX are correct.

They also have tarred up version of the data that people may be downloading, e.g. 
https://sbnarchive.psi.edu/pds4/orex/downloads_ocams/
https://sbnarchive.psi.edu/pds4/orex/downloads_tagcams/
Etc.

You can find them browsing from here: https://pds-smallbodies.astro.umd.edu/data_sb/missions/orex/index.shtml

(Note I started by googling "PDS sbn OREX data")

**Comment by jordanpadams** [comment]
Increased estimate due to issues with missing archive logs

**Comment by c-suh** [comment]
We have the correct logs now and are moving forward with the task.

**Comment by c-suh** [comment]
New logs are still being read into the database.

**Comment by c-suh** [comment]
delivered!
